version: "3.5"

services:
  api-1: &api
    image: accerqueira/rinha-de-backend-2024-q1-bash-api
    build:
      dockerfile: Dockerfile
      args:
        - SOURCE_PATH=src/api.sh
    depends_on:
      - db
    environment:
      - PORT=8081
      - WORKERS=8
      - CONNECTIONS=1000
      - DB_CONNECTION_URL=127.0.0.1:8083
      # - DB_CONNECTION_URL=db:9999
    network_mode: host
    # deploy:
    #   # replicas: 2
    #   resources:
    #     limits:
    #       # cpus: "0.5"
    #       memory: "100MB"

  api-2:
    <<: *api
    environment:
      - PORT=8082
      - WORKERS=8
      - CONNECTIONS=1000
      - DB_CONNECTION_URL=127.0.0.1:8083

  lb:
    image: accerqueira/rinha-de-backend-2024-q1-bash-lb
    build:
      dockerfile: Dockerfile
      args:
        - SOURCE_PATH=src/lb.sh
    depends_on:
      - api-1
      - api-2
    environment:
      - SERVERS=127.0.0.1:8081|127.0.0.1:8082
      - WORKERS=16
      - CONNECTIONS=10000
      # - SERVERS=api-1:9999|api-2:9999
    network_mode: host
    # ports:
    #   - "9999:9999"
    # deploy:
    #   resources:
    #     limits:
    #       # cpus: "0.25"
    #       memory: "100MB"
    # entrypoint: "socat TCP-LISTEN:9999,reuseaddr,fork,max-children=4 TCP:api:9999"

  db:
    image: accerqueira/rinha-de-backend-2024-q1-bash-db
    build:
      dockerfile: Dockerfile
      args:
        - SOURCE_PATH=src/db.sh
    environment:
      - PORT=8083
      - WORKERS=4
      - CONNECTIONS=100
      - DB_INIT_SCRIPT=
        CREATE TABLE IF NOT EXISTS clientes (
          "id" INTEGER PRIMARY KEY NOT NULL,
          "saldo" INTEGER NOT NULL,
          "limite" INTEGER NOT NULL,
          "ultimas_transacoes" JSON NOT NULL DEFAULT ('[]')
        );
        DELETE FROM clientes;
        INSERT INTO clientes VALUES(1,0,100000,'[]');
        INSERT INTO clientes VALUES(2,0,80000,'[]');
        INSERT INTO clientes VALUES(3,0,1000000,'[]');
        INSERT INTO clientes VALUES(4,0,10000000,'[]');
        INSERT INTO clientes VALUES(5,0,500000,'[]');
    network_mode: host
    # deploy:
    #   resources:
    #     limits:
    #       # cpus: "0.25"
    #       memory: "250MB"
    entrypoint: sh -c 'echo "$${DB_INIT_SCRIPT}" | sqlite3 db.sqlite3 && src/server.sh'
